fresh:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: fresh_market
    username: root
    password: a123456
  alioss:
    bucket-name: fresh-market
    access-key-id: <your-aliyun-access-key-id>
    access-key-secret: <your-aliyun-access-key-secret>
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: a123456
    database: 0
